source 'https://gems.ruby-china.com/'

gem 'rake'
gem 'asciidoctor'
gem 'asciidoctor-pdf'
gem 'asciidoctor-pdf-cjk'
gem 'asciidoctor-pdf-cjk-kai_gen_gothic'
gem 'ttfunk', '~> 1.5', '>= 1.5.1'
gem 'prawn-icon'
gem 'asciidoctor-diagram'
gem 'pygments.rb'